//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRegister.Api.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserRegister.Api.Resource.ApiResource", typeof(ApiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cidade do endereço não pode ser vazia..
        /// </summary>
        public static string ADDRESS_CITY_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS-CITY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O bairro do endereço não pode ser vazia..
        /// </summary>
        public static string ADDRESS_DISTRICT_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS-DISTRICT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O numero do endereço não pode ser vazio..
        /// </summary>
        public static string ADDRESS_NUMBER_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS-NUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código postal não pode ser vazio..
        /// </summary>
        public static string ADDRESS_POSTALCODE_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS-POSTALCODE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP deve ser um CEP válido (exemplo: 38380380)..
        /// </summary>
        public static string ADDRESS_POSTALCODE_INVALID {
            get {
                return ResourceManager.GetString("ADDRESS-POSTALCODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estado do endereço não pode ser vazio..
        /// </summary>
        public static string ADDRESS_STATE_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS-STATE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rua do endereço não pode ser vazio..
        /// </summary>
        public static string ADDRESS_STREET_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS-STREET_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado nenhum endereço com este CEP &apos;{0}&apos;..
        /// </summary>
        public static string USER_ADDRESS_NOT_FOUND_ADDRESS_BY_POSTAL_CODE {
            get {
                return ResourceManager.GetString("USER-ADDRESS-NOT_FOUND_ADDRESS_BY_POSTAL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CNPJ do usuário não pode ser vazio..
        /// </summary>
        public static string USER_CNPJ_EMPTY {
            get {
                return ResourceManager.GetString("USER-CNPJ_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CNJP do usuário deve ter &apos;{0}&apos; caracteres numéricos..
        /// </summary>
        public static string USER_CNPJ_EXCEEDED_MAXIMUM_CHARACTER {
            get {
                return ResourceManager.GetString("USER-CNPJ_EXCEEDED_MAXIMUM_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da empresa não pode ser vazio..
        /// </summary>
        public static string USER_CORPORATENAME_EMPTY {
            get {
                return ResourceManager.GetString("USER-CORPORATENAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da emrpesa deve ter no máximo &apos;{0}&apos; caracteres..
        /// </summary>
        public static string USER_CORPORATENAME_EXCEEDED_MAXIMUM_CHARACTER {
            get {
                return ResourceManager.GetString("USER-CORPORATENAME_EXCEEDED_MAXIMUM_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF do usuário não pode ser vazio..
        /// </summary>
        public static string USER_CPF_EMPTY {
            get {
                return ResourceManager.GetString("USER-CPF_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF do usuário não pode ultrapassar ou ser menor que &apos;{0}&apos; caracteres..
        /// </summary>
        public static string USER_CPF_EXCEEDED_MAXIMUM_CHARACTER {
            get {
                return ResourceManager.GetString("USER-CPF_EXCEEDED_MAXIMUM_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email não pode ser vazio..
        /// </summary>
        public static string USER_EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("USER-EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email deve ser um email válido (exemplo@exemplo.com)..
        /// </summary>
        public static string USER_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("USER-EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário não pode ser vazio..
        /// </summary>
        public static string USER_NAME_EMPTY {
            get {
                return ResourceManager.GetString("USER-NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário não pode ultrapassar &apos;{0}&apos; caracteres..
        /// </summary>
        public static string USER_NAME_EXCEEDED_MAXIMUM_CHARACTER {
            get {
                return ResourceManager.GetString("USER-NAME_EXCEEDED_MAXIMUM_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O DDD do telefone não pode ser vazio..
        /// </summary>
        public static string USER_PHONE_DDD_EMPTY {
            get {
                return ResourceManager.GetString("USER-PHONE-DDD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O DDD não pode ultrapassar &apos;{0}&apos; caracteres..
        /// </summary>
        public static string USER_PHONE_DDD_EXCEEDED_MAXIMUM_CHARACTER {
            get {
                return ResourceManager.GetString("USER-PHONE-DDD_EXCEEDED_MAXIMUM_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O numero de telefone não pode ser vazio..
        /// </summary>
        public static string USER_PHONE_NUMBERPHONE_EMPTY {
            get {
                return ResourceManager.GetString("USER-PHONE-NUMBERPHONE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O numero de telefone não pode ultrapassar &apos;{0}&apos; caracteres..
        /// </summary>
        public static string USER_PHONE_NUMBERPHONE_EXCEEDED_MAXIMUM_CHARACTER {
            get {
                return ResourceManager.GetString("USER-PHONE-NUMBERPHONE_EXCEEDED_MAXIMUM_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário com este mesmo CPF &apos;{0}&apos; ou Email &apos;{1}&apos;..
        /// </summary>
        public static string USER_USER_EXISTING_BY_CPF_OR_EMAIL {
            get {
                return ResourceManager.GetString("USER-USER_EXISTING_BY_CPF_OR_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe usuário com estes mesmos numeros de telefones: &apos;{0}&apos;..
        /// </summary>
        public static string USER_USERPHONE_EXISTINGS {
            get {
                return ResourceManager.GetString("USER-USERPHONE_EXISTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário deve possuir pelo menos um telefone de contato..
        /// </summary>
        public static string USER_USERPHONES_EMPTY {
            get {
                return ResourceManager.GetString("USER-USERPHONES_EMPTY", resourceCulture);
            }
        }
    }
}
